name: Linting

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: 'src test include'
        exclude: 'test/lib/munit.*'
        extensions: 'c,h'
        clangFormatVersion: 14
        style: file
